default: build

[group('build')]
build: alex 
  hpack
  cabal build Haskell-exe 

[positional-arguments]
ghci *args='': alex
  hpack
  cabal repl {{args}}

clean:
  cabal clean
  rm -rf ./dist/**

alex:
  alex ./Alex/Lexer.x  -o ./src/Parser/Lexer.hs

parse: build 
  cabal run Haskell-exe
