default: build

[group('build')]
build: alex happy  
  hpack
  cabal build Haskell-exe 

[positional-arguments]
ghci *args='': alex happy 
  hpack
  cabal repl {{args}}

clean:
  cabal clean
  rm -rf ./dist/**

alex:
  alex ./Alex/Lexer.x  -o ./src/Parser/Lexer.hs

happy: alex 
  happy -i ./Alex/Parser.y -o ./src/Parser/Parser.hs

parse *args='./programs/*' : build 
  cabal run Haskell-exe -- {{args}}
